### ISSUE TITLE
[ISSUE | 0.1.0-rc.11 V4] <Action> class missing `toggled` method

### ISSUE THREAD

**Issue by KitCat962** [GrandpaScout/FiguraRewriteVSDocs#2]
## **Issue:**
This one thing isn't documented at all.

## **Why:**
I could not find it in the `.vscode\docs\figura\action_wheel\action.lua` file and code that uses it gives a warning.

## **Environment:**
**Editor:** VSCode
**Platform:** Windows 10
**Figura Version:** 0.1.0-rc.11
**Docs Version:** 0.1.0-rc.11 V4

## **Helping Out:**

- [ ] I can replicate this issue on other environments.
  * Env 1
  * Env 2
  * Env N
- [x] I know how to read Java code.
- [x] I know how to read and write LuaCats documentation and annotations.
- [x] I know how to make a pull request.

## **Additional Info:**
I am drowning in all of this Issue bloat. Send hellp.

**Comment by GrandpaScout** [comment]
Yeah, I don't like the current issue templates right now myself. It used to be worse lmao.

Anyways, I'll check this out.
