### ISSUE TITLE
0.1.0-rc11 V6 functions assigned to the `pings` table do not show up in autocompletion box

### ISSUE THREAD

**Issue by KitCat962** [GrandpaScout/FiguraRewriteVSDocs#4]
Functions added to the `pings` table do not show up in the autocomplete box when typing `pings.`.
I can understand why it does this as you have made the `pings` table a class, but it really needs autocomplete support.
![image](https://user-images.githubusercontent.com/94943674/202871683-c576c823-1741-4fb0-9953-6230db409ef7.png)

**Comment by GrandpaScout** [comment]
Seems like a recent LLS update might have broke this as I remember testing this while creating the docs originally.
I'll see what I can do about it.
