### ISSUE TITLE
0.1.0rc12 v1 functions registered the `newindex` way get marked as a duplicate field

### ISSUE THREAD

**Issue by KitCat962** [GrandpaScout/FiguraRewriteVSDocs#9]
probably already known, but marked as an issue regardless.
![image](https://user-images.githubusercontent.com/94943674/205184734-029285f3-b624-4f1a-86c1-189abada0248.png)

odd thing is it didn't seem to do this before. Language server must have updated or something

**Comment by GrandpaScout** [comment]
Not much I can do (that I have found) about that currently, one fix would be to put
```lua
---@diagnostic disable-next-line: duplicate-set-field
```
before the assignment.

I will keep this open just in case there is some update that can fix this.

**Comment by GrandpaScout** [comment]
Completely forgot about this, but this was resolved in `cf4556e` by just completely disabling the error.
I know, great fix 10/10.
